# Generated by Django 5.1 on 2024-11-12 14:17

import django.db.models.deletion
import simple_helpdesk.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=1000)),
            ],
            bases=(models.Model, simple_helpdesk.models.AuditableEntity),
        ),
        migrations.CreateModel(
            name='TicketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('sort_order', models.IntegerField(default=1)),
                ('colour', models.CharField(max_length=10)),
            ],
            bases=(models.Model, simple_helpdesk.models.AuditableEntity),
        ),
        migrations.CreateModel(
            name='Swimlane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sort_order', models.IntegerField(default=1)),
                ('swimlane_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_helpdesk.project')),
            ],
            bases=(models.Model, simple_helpdesk.models.AuditableEntity),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_assignee', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_reporter', to=settings.AUTH_USER_MODEL)),
                ('ticket_swimlane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_helpdesk.swimlane')),
                ('ticket_priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simple_helpdesk.ticketpriority')),
            ],
            bases=(models.Model, simple_helpdesk.models.AuditableEntity),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2500)),
                ('parent_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_helpdesk.ticket')),
            ],
            bases=(models.Model, simple_helpdesk.models.AuditableEntity),
        ),
    ]
