# Generated by Django 5.1 on 2024-11-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_priority',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='TicketPriority',
        ),
    ]
